apiVersion: v1
kind: ReplicationController
metadata:
  name: scdf
spec:
  replicas: 1
  selector:
    name: scdf
  template:
    metadata:
      labels:
        name: scdf
    spec:
      containers:
      - name: scdf
        image: springcloud/spring-cloud-dataflow-server-kubernetes
        imagePullPolicy: Always
        ports:
        - containerPort: 9393
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: SPRING_CLOUD_DATAFLOW_FEATURES_ANALYTICS_ENABLED
          value: 'true'
        - name: SPRING_CLOUD_DEPLOYER_KUBERNETES_MEMORY
          value: 640Mi
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
          value: 'true'
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_NAME
          value: scdf-secrets
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
          value: scdf-config
