apiVersion: v1
kind: ReplicationController
metadata:
  name: scdf
spec:
  replicas: 1
  selector:
    name: scdf
  template:
    metadata:
      labels:
        name: scdf
    spec:
      containers:
      - name: scdf
        image: springcloud/spring-cloud-dataflow-server-kubernetes
        imagePullPolicy: Always
        ports:
        - containerPort: 9393
        env:
        - name: KUBERNETES_MASTER
          value: '<<URL-for-Kubernetes-master>>'
        - name: KUBERNETES_NAMESPACE
          value: 'default'
        - name: SPRING_APPLICATION_JSON
          value: '{"spring.datasource.url":"jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/test","spring.datasource.driverClassName":"org.mariadb.jdbc.Driver","spring.datasource.username":"<<mysql-username>>","spring.datasource.password":"<<mysql-password>>","spring.redis.host":"${REDIS_SERVICE_HOST}","spring.redis.port":"${REDIS_SERVICE_PORT}","spring.cloud.deployer.kubernetes.memory":"640Mi"}'
